dist:
  name: otelcol-dev
  description: Basic OTel Collector distribution for Developers
  output_path: ./otelcol-dev
  otelcol_version: 0.106.1

exporters:
  - gomod:
      go.opentelemetry.io/collector/exporter/debugexporter v0.106.1
  - gomod:
      go.opentelemetry.io/collector/exporter/otlpexporter v0.106.1
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/exporter/prometheusremotewriteexporter v0.106.1

processors:
  - gomod:
      go.opentelemetry.io/collector/processor/batchprocessor v0.106.1

receivers:
  - gomod:
      go.opentelemetry.io/collector/receiver/otlpreceiver v0.106.1
  - gomod:
      github.com/open-telemetry/opentelemetry-collector-contrib/receiver/prometheusreceiver v0.106.1
  - gomod:
      github.com/adarshsingh2/custom-collector/ucpmetricreceiver v0.0.1
  
